# Generated by Django 5.2.6 on 2025-09-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=30)),
                ('dateofbirth', models.DateField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
    ]
